const TargetMap={hostname:chrome.i18n.getMessage("rTargetHostname"),href:chrome.i18n.getMessage("rTargetHref"),title:chrome.i18n.getMessage("rTargetTitle"),title_ignorecase:chrome.i18n.getMessage("rTargetTitleIgnoreCase")},MethodMap={includes:chrome.i18n.getMessage("rMethodIncludes"),startsWith:chrome.i18n.getMessage("rMethodStartsWith"),endsWith:chrome.i18n.getMessage("rMethodEndsWith"),equal:chrome.i18n.getMessage("rMethodEqual"),regex:chrome.i18n.getMessage("rMethodRegex")};
function fillTargetForTitleMatch(a){a.target=a.ignoreCase?"title_ignorecase":"title"}
class RuleList{static init(){RuleList.ruleTp=document.getElementById("rule-tp").content;RuleList.container=document.getElementById("rule-list");RuleList.refresh();RuleList.delConfirmModal=new bootstrap.Modal(document.getElementById("delete-confirm"));document.getElementById("btn-delete-yes").addEventListener("click",RuleList.remove);RuleList.helpModal=new bootstrap.Modal(document.getElementById("help-modal"),{backdrop:!0,keyboard:!0});document.getElementById("btn-help").addEventListener("click",RuleList.showHelp);
RuleList.fileInput=document.querySelector("input[type=file]");RuleList.fileInput.addEventListener("change",RuleList.importJson);let [a,b]=document.querySelectorAll("#data-menu button");a.addEventListener("click",d=>RuleList.fileInput.click());b.addEventListener("click",d=>RuleStore.exportJson())}static async refresh(){RuleList.container.innerHTML="";let a=await RuleStore.getAll();for(let b of a)RuleList.add(b)}static createMatchRow(a,b){let d=document.createElement("tr"),c=document.createElement("th"),
e=document.createElement("td"),f=document.createElement("td"),g=document.createElement("td");c.scope="row";c.textContent=b;e.textContent=TargetMap[a.target];f.textContent=MethodMap[a.method];g.textContent=a.value;g.classList.add("text-truncate");d.appendChild(c);d.appendChild(e);d.appendChild(f);d.appendChild(g);return d}static create(a){let b=RuleList.ruleTp.cloneNode(!0);initMsg(b);let d=b.querySelector(".rule");d.id=a.id;let [c,e]=b.querySelectorAll("legend > span");a.groupColor?c.style.backgroundColor=
ColorMap[a.groupColor]:c.classList.add("border");e.textContent=`${a.ruleName} (${a.groupName})`;let f=b.querySelector("tbody"),g=0;if(a.urlMatches)for(let h of a.urlMatches)g++,f.appendChild(RuleList.createMatchRow(h,g));if(a.titleMatches)for(let h of a.titleMatches)g++,fillTargetForTitleMatch(h),f.appendChild(RuleList.createMatchRow(h,g));let [l,m,k]=b.querySelectorAll("button,input");l.addEventListener("click",RuleList.edit);m.addEventListener("click",h=>RuleList.removeConfirm(a));k.checked=a.enabled??
!0;RuleList.setUIEnable(d,k.checked);k.addEventListener("click",RuleList.toggleEnable);return b}static setUIEnable(a,b){b?a.classList.remove("disabled"):a.classList.add("disabled")}static toggleEnable(a){a=this.closest(".rule");RuleStore.setEnabled(a.id,this.checked);RuleList.setUIEnable(a,this.checked)}static add(a){RuleList.container.appendChild(RuleList.create(a))}static async edit(a){a=this.closest(".rule").id;(a=await RuleStore.get(a))&&Rule.edit(a)}static removeConfirm(a){RuleList.toDelRuleId=
a.id;document.querySelector("#delete-confirm .modal-title").textContent=chrome.i18n.getMessage("rDelConfirm",[a.ruleName]);RuleList.delConfirmModal.show()}static async remove(a){a.preventDefault();if(a=document.getElementById(RuleList.toDelRuleId))try{await RuleStore.remove(RuleList.toDelRuleId),a.remove(),RuleList.delConfirmModal.hide()}catch(b){alert("Delete fail: "+b)}}static update(a){let b=document.getElementById(a.id);a=RuleList.create(a);b?RuleList.container.replaceChild(a,b):RuleList.container.appendChild(a)}static showHelp(a){RuleList.helpModal.show()}static async importJson(a){if(a=
this.files[0])if(this.value=null,a.name.endsWith(".json"))if(1E5<a.size)console.log("file size > 100000 bytes");else try{await RuleStore.importJson(a),RuleList.refresh()}catch(b){console.log(b)}else console.log("file type is not json")}}
class Rule{static init(){document.getElementById("btn-add").addEventListener("click",Rule.add);document.getElementById("edit-modal-save").addEventListener("click",Rule.save);Rule.modal=new bootstrap.Modal(document.getElementById("edit-modal"),{backdrop:"static",keyboard:!1});Rule.matchTp=document.getElementById("matching-tp").content;Rule.matchContainer=document.getElementById("edit-modal-matching");Rule.ruleName=document.getElementById("edit-rule-name");Rule.groupName=document.getElementById("edit-group-name");
Rule.groupColor=document.getElementById("edit-group-color")}static addMatch(a){let b=Rule.matchTp.cloneNode(!0);initMsg(b);let [d,c]=b.querySelectorAll(".pointer");d.addEventListener("click",e=>Rule.addMatch());c.addEventListener("click",Rule.removeMatch);if(a){let [e,f,g]=b.querySelectorAll("select,input");e.value=a.target;f.value=a.method;g.value=a.value}Rule.matchContainer.appendChild(b)}static removeMatch(a){a.preventDefault();a=this.closest(".row");1<Rule.matchContainer.childElementCount&&a.remove()}static add(a){a.preventDefault();
Rule.action=void 0;Rule.lastGroupName=void 0;Rule.clearAllInvalid();Rule.ruleName.value="";Rule.groupName.value="";Rule.groupColor.value="auto";Rule.matchContainer.innerHTML="";Rule.addMatch();Rule.modal.show()}static edit(a){Rule.action=a.id;Rule.lastGroupName=a.groupName;Rule.clearAllInvalid();Rule.ruleName.value=a.ruleName;Rule.groupName.value=a.groupName;Rule.groupColor.value=a.groupColor?a.groupColor:"auto";Rule.matchContainer.innerHTML="";if(a.urlMatches)for(let b of a.urlMatches)Rule.addMatch(b);
if(a.titleMatches)for(let b of a.titleMatches)fillTargetForTitleMatch(b),Rule.addMatch(b);Rule.modal.show()}static markAsInvalid(a){a.classList.add("is-invalid")}static isAllValid(){return 0===document.querySelectorAll("#edit-modal .is-invalid").length}static clearAllInvalid(){let a=document.querySelectorAll("#edit-modal .is-invalid");for(let b of a)b.classList.remove("is-invalid")}static getRuleFromEditorAndValidate(){var a=Object.keys(ColorMap);const b=["hostname","href","title","title_ignorecase"],
d=["includes","startsWith","endsWith","equal","regex"];let c={ruleName:Rule.ruleName.value.trim(),groupName:Rule.groupName.value.trim()};var e=Rule.groupColor.value;"auto"!==e&&(c.groupColor=e);c.ruleName||Rule.markAsInvalid(Rule.ruleName);c.groupName||Rule.markAsInvalid(Rule.groupName);c.groupColor&&!a.includes(c.groupColor)&&Rule.markAsInvalid(Rule.groupColor);a=[];e=[];for(let g of Rule.matchContainer.children){let [l,m,k]=g.querySelectorAll("select,input");var f=l.value;let h=m.value,n=k.value.trim();
"title"===f?e.push({method:h,value:n}):"title_ignorecase"===f?e.push({method:h,value:n,ignoreCase:!0}):a.push({target:f,method:h,value:n});0<a.length&&(c.urlMatches=a);0<e.length&&(c.titleMatches=e);b.includes(f)||Rule.markAsInvalid(l);d.includes(h)||Rule.markAsInvalid(m);f=k.nextElementSibling;n||(f.textContent=chrome.i18n.getMessage("rValueEmptyInvalid"),Rule.markAsInvalid(k))}return c}static async save(a){a.preventDefault();Rule.clearAllInvalid();let b=Rule.getRuleFromEditorAndValidate();if(Rule.isAllValid()){void 0!==
Rule.action&&(b.id=Rule.action,b.enabled=document.querySelector(`#${b.id} input`).checked);try{b=await RuleStore.save(b),RuleList.update(b),Rule.modal.hide(),void 0!==Rule.lastGroupName&&Rule.lastGroupName!==b.groupName&&chrome.tabGroups.query({title:Rule.lastGroupName},function(d){for(let c of d)chrome.tabGroups.update(c.id,{title:b.groupName})})}catch(d){alert("Save fail: "+d)}}}}
function initMsg(a=document){a=a.querySelectorAll("[data-i18n]");for(const b of a)b.textContent=chrome.i18n.getMessage(b.dataset.i18n)}function initMsgHtml(a=document){a=a.querySelectorAll("[data-i18n-html]");for(const b of a)b.innerHTML=chrome.i18n.getMessage(b.dataset.i18nHtml)}function initInputPlaceholder(a=document){a=a.querySelectorAll("input[data-i18n-ph]");for(const b of a)b.placeholder=chrome.i18n.getMessage(b.dataset.i18nPh)}
function init(){initMsg();initMsgHtml();initInputPlaceholder();RuleList.init();Rule.init();document.body.classList.remove("d-none")}init();
